Table obras_social {
	id_obra_social integer [ pk, increment, not null, unique ]
	nombre varchar(255) [ not null ]
}

Table paciente {
	id_paciente integer [ pk, increment, not null, unique ]
	historia_clinica varchar [ not null, unique ]
	nombre varchar(255) [ not null ]
	apellido varchar(255) [ not null ]
	dni varchar(20) [ not null, unique ]
	email varchar(255)
	telefono varchar(20)
	fecha_nacimiento date [ not null ]
	numero_afiliado varchar(50) [ not null ]
}

Table medico {
	id_medico integer [ pk, increment, not null, unique ]
	nombre varchar(255) [ not null ]
	apellido varchar(255) [ not null ]
	matricula varchar [ not null ]
	id_especialidad integer [ not null ]
}

Table turno {
	id_turno integer [ pk, increment, not null, unique ]
	fecha date [ not null ]
	hora time [ not null ]
	id_estado integer [ not null ]
	motivo text [ not null ]
	id_paciente integer [ not null ]
	id_medico integer [ not null ]
	id_sede integer
	id_secretario integer [ not null ]
}

Table secretario {
	id_secretario integer [ pk, increment, not null, unique ]
	nombre varchar(255) [ not null ]
	apellido varchar(255) [ not null ]
	id_sede integer [ not null ]
}

Table sede {
	id_sede integer [ pk, increment, not null, unique ]
	nombre varchar(255) [ not null ]
	direccion varchar(255)
	telefono varchar(20)
}

Table especialidad {
	id_especialidad integer [ pk, increment, not null, unique ]
	nombre varchar(255) [ not null ]
	descripcion varchar
}

Table estados {
	id_estado integer [ pk, increment, not null, unique ]
	nombre varchar(255) [ not null ]
}

Table paciente_enfermedad_cronica {
	id_paciente integer [ pk, not null ]
	id_enfermedad_cronica integer [ pk, not null ]
	fecha_diagnostico date

	indexes {
		(id_paciente, id_enfermedad_cronica) [ name: 'paciente_enfermedad_cronica_index_0' ]
	}
}

Table enfermedad_cronica {
	id_enfermedad_cronica integer [ pk, increment, not null, unique ]
	nombre varchar(255) [ not null ]
	descripcion text
}

Table evolucion_clinica {
	id_evolucion integer [ pk, increment, not null, unique ]
	id_paciente integer [ not null ]
	id_medico integer [ not null ]
	id_obra_social integer [ not null ]
	numero_afiliado varchar [ not null ]
	fecha date [ not null ]
	hora time [ not null ]
	motivo_consulta varchar(255) [ not null ]
	diagnostico text [ not null ]
	tratamiento text
	notas_adicionales text
}

Table afiliacion_obra_social {
	id_paciente integer [ pk, increment, not null, unique ]
	id_obra_social integer [ pk ]
	numero_afiliado varchar
	fecha_alta date
	fecha_baja date
}

Ref se asigna {
	medico.id_especialidad > especialidad.id_especialidad [ delete: cascade, update: restrict ]
}

Ref pertenece a {
	secretario.id_sede > sede.id_sede [ delete: cascade, update: restrict ]
}

Ref dado a  {
	turno.id_paciente > paciente.id_paciente [ delete: cascade, update: restrict ]
}

Ref atendido por {
	medico.id_medico > turno.id_medico [ delete: cascade, update: restrict ]
}

Ref en {
	turno.id_sede > sede.id_sede [ delete: cascade, update: restrict ]
}

Ref dado por {
	turno.id_secretario > secretario.id_secretario [ delete: cascade, update: set null ]
}

Ref padece {
	paciente_enfermedad_cronica.id_paciente > paciente.id_paciente [ delete: cascade, update: cascade ]
}

Ref registra {
	paciente_enfermedad_cronica.id_enfermedad_cronica > enfermedad_cronica.id_enfermedad_cronica [ delete: cascade, update: restrict ]
}

Ref tiene {
	turno.id_estado > estados.id_estado [ delete: cascade, update: cascade ]
}

Ref de un {
	paciente.id_paciente > evolucion_clinica.id_paciente [ delete: cascade, update: cascade ]
}

Ref realizada por {
	medico.id_medico > evolucion_clinica.id_medico [ delete: cascade, update: restrict ]
}

Ref se registra {
	obras_social.id_obra_social < afiliacion_obra_social.id_obra_social [ delete: no action, update: no action ]
}

Ref se afilia {
	afiliacion_obra_social.id_paciente > paciente.id_paciente [ delete: no action, update: no action ]
}

Ref se factura con {
	obras_social.id_obra_social - evolucion_clinica.id_obra_social [ delete: no action, update: no action ]
}
